### PR TITLE
new options added [--artist, --character, --parody, --group]

### PR DESCRIPTION
**Pull request by Alocks**
Added new options and now is possible multiple arguments in -tag --artist, --character, --parody, --group, separating by comma.

eg: --artist mdo-h,tamano kedama

Wondering if has a better approach for multiple arguments using optparse.OptionParser(?)
FeelsBad using if ',' in tag_name: tag_name.split(';')

### CODE REVIEW

**Comment by RicterZ** [comment]
Resolve this conflict please. This PR will be merged to dResolve this conflict please. This PR will be merged to dev branch.ev branch.

**Comment by Alocks** [comment]
Removed the code in parse module, because i do not have write access for the dev branch (need to be added as collaborator).

The code written won't work without index=0 argument and TAG_URL[index]

```
def tag_parser(tag_name, max_page=1, index=0):
    result = []
    tag_name = tag_name.lower()
    if ',' in tag_name:
        tag_name = [i.strip().replace(' ', '-') for i in tag_name.split(',')]
    else: tag_name = tag_name.replace(' ', '-')
        
    for p in range(1, max_page + 1):
        logger.debug('Fetching page {0} for doujinshi with tag \'{1}\''.format(p, tag_name))
        if isinstance(tag_name, str):
            response = request('get', url='%s/%s/?page=%d' % (constant.TAG_URL[index], tag_name, p)).content
            result += _get_title_and_id(response)
        else:
            for i in tag_name:
                response = request('get', url='%s/%s/?page=%d' % (constant.TAG_URL[index], i, p)).content
                result += _get_title_and_id(response)
```

**Comment by RicterZ** [comment]
https://travis-ci.org/RicterZ/nhentai/jobs/595936345#L571

` nhentai --tag lolicon --sorting popular`

**Comment by Alocks** [comment]
> https://travis-ci.org/RicterZ/nhentai/jobs/595936345#L571
> 
> ` nhentai --tag lolicon --sorting popular`

I replied above why it won't work... I can't change parse.py without your permission. Or adding me as collaborator, or changing parse.py file access....

**Comment by RicterZ** [comment]
added :)

**Pull request merged**
