### PR TITLE
Create a main viewer contains all the sub index.html and thumb pic

### PR DESCRIPTION
**Pull request by symant233**
Usage: 
1. `cd` into your folder which contains all your doujinshi folders.
2. run `nhentai --gen-main`
3. open the `main.html` and see how awesome it is! (just like nhentai favorite page)

### CODE REVIEW

**Comment by symant233** [comment]
You can set this to default just like generate `index.html` if you like. 
You can change the `--gen-main` to a better name(my sounds wierd... ). 
And don't forget update `readme.md` to announce this new feature.

**Comment by symant233** [comment]
If you'd like to set this default then add this new line 69.
image

**Comment by symant233** [comment]
BTW, this solves #52 to add a alias for `http://127.0.0.1:1080`
use `--proxy 'default'` or `--proxy 'd'` instead of `--proxy "http://127.0.0.1:1080"`

**Comment by symant233** [comment]
Wait a minute... I'll fix it.

**Comment by RicterZ** [comment]
Hi @symant233 
I updated nhentai, removed / added some options, and there is a conflicted. Could you pull the new version of nhentai fix it?

**Comment by symant233** [comment]
Build failed when using `python 2.7`. Error occurs when decode Chinese characters. But `python 3.x` works fine. I'll take a look and fix that soon.

**Comment by symant233** [comment]
Solved by ignore `python2.x` to generate main viewer.
It can be solved by add these lines in `utils.py`:
```
    if sys.version_info < (3, 0):
        reload(sys)
        sys.setdefaultencoding('utf-8')
```

But this will show error in vscode linter (cause py3 removed reload built-in function).

> BTW, I tested py2, the cml output Japanese and Chinese will be garbled.

**Comment by RicterZ** [comment]
image
It's not very good for generating html files in all sub directories...

**Comment by symant233** [comment]
It checks only when index.html occurs then generate main.html 
If the sub folder doesn’t contain an index it will just warning and skip that folder.

**Comment by symant233** [comment]
The commit beyond ignore other folder which is not doujinshi folders. 
`main.html` will not been create if none `index.html` found.

**Comment by RicterZ** [comment]
Add some test cases into .travis.ci of your PR :)
I'll merge it after all the test cases passed

**Pull request merged**
