### PR TITLE
Changed parser option checks to allow artist search

### PR DESCRIPTION
**Pull request by Spyridion**
I noticed the if checks stop the artist tag from being used. I added the nots to allow the artist search to continue to the legacy search function.

### CODE REVIEW

**Comment by Spyridion** [comment]
Hi, I just noticed that the dev branch doesn't have the artist specific changes from master branch.

**Comment by Spyridion** [comment]
Will you be cherry picking from dev into master?

**Comment by RicterZ** [comment]
Merged to master branch.

Seems better to use `soup = BeautifulSoup(s,  "html.parser")` to parse html content, this way isn't need lxml dependency

**Comment by Spyridion** [comment]
Yeah, that makes sense. There were a couple changes I didn't notice between dev and main when I made this pr.

**Pull request merged**
